### ISSUE TITLE
pressing F2 or F3 => FATAL: float argument required, not NoneType

### ISSUE THREAD

**Issue by pmpetit** [julmon/pg_activity#113]
Hello,
for information ,
executed with " --rds option "
Traceback (most recent call last):
  File "./pg_activity", line 350, in main
    db_info['total_size']
  File "pg_activity/pgactivity/UI.py", line 1954, in refresh_window
    self.__refresh_line(proc, flag, indent, 'default')
  File "pg_activity/pgactivity/UI.py", line 2094, in __refresh_line
    " %.6f " % (process['duration'],),
TypeError: float argument required, not NoneType
FATAL: float argument required, not NoneType

it is because of grants, using a superuser do not show any errors

**Comment by julmon** [comment]
Thanks for the report, it should be fixed now.
